"""
Text-to-Speech generator using Gemini's multi-speaker TTS API.

Each :class:`~tts_podcast.llm_summarizer.DialogueChunk` is converted into
raw PCM audio bytes (24 kHz, mono, 16-bit signed little-endian) by calling
the configured Gemini TTS model with a
:class:`~google.genai.types.MultiSpeakerVoiceConfig`.

A natural-language audio profile preamble is prepended to each chunk before
sending to the TTS API.  This preamble defines each host's personality,
the scene context, and director's notes so that Gemini TTS interprets inline
emotional cues (e.g. "(avec enthousiasme)") generated by the LLM with the
right character voices.

Chunks are processed in parallel using a thread pool (up to 5 concurrent
requests) to reduce total wall-clock time.
"""

from __future__ import annotations

import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import TYPE_CHECKING, Any

from google import genai
from google.genai import types

from tts_podcast.retry import gemini_retry

if TYPE_CHECKING:
    from rich.progress import Progress
    from tts_podcast.llm_summarizer import DialogueChunk
    from tts_podcast.token_tracker import TokenTracker

logger = logging.getLogger(__name__)

# Maximum number of concurrent TTS API requests.
_TTS_MAX_WORKERS = 5


def _build_tts_prompt(chunk_text: str, gemini_cfg: dict) -> str:
    """
    Prepend a natural-language audio profile preamble to a dialogue chunk.

    The preamble instructs Gemini TTS to apply consistent speaker personalities
    and honour inline emotional cues written in parentheses within the dialogue.

    Parameters
    ----------
    chunk_text : str
        The raw dialogue text for this chunk (e.g. "Alex: (avec enthousiasme) ...").
    gemini_cfg : dict
        Resolved Gemini configuration section.  Uses ``speaker1``, ``speaker2``
        (each with ``name`` and optional ``personality`` keys), ``language``
        (default ``"French"``), an optional ``tts_style.scene`` string, and an
        optional ``tts_style.pace`` string that provides a natural-language
        description of the desired speaking pace (e.g. ``"slow and deliberate"``).
        When absent, defaults to ``"natural"``.

    Returns
    -------
    str
        The preamble followed by the dialogue text, ready for the TTS API.
    """
    s1 = gemini_cfg["speaker1"]
    s2 = gemini_cfg["speaker2"]
    tts_style = gemini_cfg.get("tts_style", {})
    scene = tts_style.get("scene", "")
    pace = tts_style.get("pace", "natural")
    language = gemini_cfg.get("language", "French")

    s1_personality = s1.get("personality", "enthusiastic and curious")
    s2_personality = s2.get("personality", "analytical and thoughtful")

    preamble = (
        f"Audio profile: Two hosts of a {language} tech podcast, speaking in {language}.\n"
        f"{s1['name']} is {s1_personality}.\n"
        f"{s2['name']} is {s2_personality}.\n"
    )
    if scene:
        preamble += f"Scene: {scene}\n"
    preamble += (
        f"Director's notes: Conversational pace — {pace}; speak clearly, "
        "allow a natural beat between sentences so the listener can absorb each idea. "
        "Genuine reactions, honour any emotional cues written in parentheses in the dialogue.\n\n"
    )
    return preamble + chunk_text


def _generate_chunk_audio(
    chunk: DialogueChunk,
    client: genai.Client,
    gemini_cfg: dict,
    voice_config: types.MultiSpeakerVoiceConfig,
    temperature: float,
) -> tuple[bytes, Any]:
    """
    Generate PCM audio for a single dialogue chunk.

    Builds the TTS prompt, calls the Gemini TTS API with retry, and returns
    the raw PCM bytes together with the response usage metadata for token
    accounting.

    Parameters
    ----------
    chunk : DialogueChunk
        The dialogue chunk to synthesise.
    client : genai.Client
        Authenticated Gemini client.
    gemini_cfg : dict
        Resolved Gemini configuration (needs ``tts_model`` key).
    voice_config : types.MultiSpeakerVoiceConfig
        Pre-built multi-speaker voice configuration.
    temperature : float
        Sampling temperature for the TTS model.

    Returns
    -------
    tuple[bytes, Any]
        ``(pcm_bytes, usage_metadata)`` where ``pcm_bytes`` is raw 24 kHz /
        mono / 16-bit LE audio and ``usage_metadata`` is the
        ``response.usage_metadata`` object (may be ``None``).

    Raises
    ------
    RuntimeError
        If the TTS API returns an unexpected response structure.
    """
    tts_prompt = _build_tts_prompt(chunk.text, gemini_cfg)
    logger.debug(
        "Generating TTS for chunk %d (%d bytes text, %d bytes with preamble)",
        chunk.index,
        len(chunk.text.encode("utf-8")),
        len(tts_prompt.encode("utf-8")),
    )

    @gemini_retry
    def _call() -> genai.types.GenerateContentResponse:
        return client.models.generate_content(
            model=gemini_cfg["tts_model"],
            contents=tts_prompt,
            config=types.GenerateContentConfig(
                response_modalities=["AUDIO"],
                temperature=temperature,
                speech_config=types.SpeechConfig(
                    multi_speaker_voice_config=voice_config,
                ),
            ),
        )

    response = _call()

    try:
        pcm_bytes: bytes = response.candidates[0].content.parts[0].inline_data.data
    except (IndexError, AttributeError) as exc:
        raise RuntimeError(
            f"Unexpected TTS response structure for chunk {chunk.index}: {exc}"
        ) from exc

    logger.info(
        "Chunk %d: received %d bytes of PCM audio",
        chunk.index,
        len(pcm_bytes),
    )
    return pcm_bytes, response.usage_metadata


def generate_audio_chunks(
    chunks: list[DialogueChunk],
    gemini_cfg: dict,
    token_tracker: TokenTracker | None = None,
    progress: Progress | None = None,
    task_id: Any = None,
) -> list[bytes]:
    """
    Convert a list of dialogue chunks into raw PCM audio bytes using Gemini TTS.

    Each chunk is sent as a separate TTS request so that the 4 000-byte text
    limit is respected.  Requests are issued in parallel (up to
    :data:`_TTS_MAX_WORKERS` concurrent workers) and results are returned in
    the same order as the input.  A natural-language audio profile preamble is
    prepended to each chunk to give the TTS model personality and emotional
    context.

    Parameters
    ----------
    chunks : list[DialogueChunk]
        Ordered dialogue chunks produced by
        :func:`~tts_podcast.llm_summarizer.generate_dialogue`.
    gemini_cfg : dict
        Resolved Gemini configuration with keys:
        ``api_key``, ``tts_model``, ``speaker1`` ({``name``, ``voice``,
        ``personality``}), ``speaker2`` ({``name``, ``voice``, ``personality``}),
        ``language`` (default ``"French"``), and optional ``tts_style``
        ({``scene``, ``temperature``}).
    token_tracker : TokenTracker or None, optional
        When provided, records token usage for every TTS API call.
    progress : rich.progress.Progress or None, optional
        A rich :class:`~rich.progress.Progress` instance.  When provided,
        ``task_id`` must also be supplied and will be advanced once per
        completed chunk.
    task_id : Any, optional
        Task identifier returned by ``progress.add_task()``.

    Returns
    -------
    list[bytes]
        One PCM bytes object per input chunk, in the same order.
        Each bytes object is raw 24 kHz / mono / 16-bit signed little-endian audio.

    Raises
    ------
    RuntimeError
        If the Gemini API returns an unexpected response structure for any chunk.

    Examples
    --------
    >>> audio_chunks = generate_audio_chunks(dialogue_chunks, gemini_cfg)
    >>> len(audio_chunks) == len(dialogue_chunks)
    True
    """
    client = genai.Client(api_key=gemini_cfg["api_key"])

    speaker1_cfg = gemini_cfg["speaker1"]
    speaker2_cfg = gemini_cfg["speaker2"]
    temperature = gemini_cfg.get("tts_style", {}).get("temperature", 1.0)

    voice_config = types.MultiSpeakerVoiceConfig(
        speaker_voice_configs=[
            types.SpeakerVoiceConfig(
                speaker=speaker1_cfg["name"],
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=speaker1_cfg["voice"],
                    )
                ),
            ),
            types.SpeakerVoiceConfig(
                speaker=speaker2_cfg["name"],
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name=speaker2_cfg["voice"],
                    )
                ),
            ),
        ]
    )

    if not chunks:
        return []

    max_workers = min(_TTS_MAX_WORKERS, len(chunks))
    logger.info(
        "Generating TTS for %d chunk(s) with up to %d worker(s)…",
        len(chunks),
        max_workers,
    )

    # Submit all chunks to the thread pool.  Use as_completed so the
    # progress bar advances as soon as *any* chunk finishes, then
    # reassemble results in the original order for audio sequencing.
    results: dict[int, bytes] = {}
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_index = {
            executor.submit(
                _generate_chunk_audio,
                chunk,
                client,
                gemini_cfg,
                voice_config,
                temperature,
            ): i
            for i, chunk in enumerate(chunks)
        }
        for future in as_completed(future_to_index):
            idx = future_to_index[future]
            pcm_bytes, usage_metadata = future.result()
            results[idx] = pcm_bytes
            if token_tracker is not None:
                token_tracker.record_usage(gemini_cfg["tts_model"], usage_metadata)
            if progress is not None and task_id is not None:
                progress.advance(task_id)
                if token_tracker is not None:
                    progress.update(
                        task_id,
                        description=f"[cyan]TTS synthesis[/cyan] — {token_tracker.live_line()}",
                    )

    return [results[i] for i in range(len(chunks))]
